### ISSUE TITLE
Problems with Makefile and server.go run 

### ISSUE THREAD

**Issue by assist726** [ldsec/lattigo-polls-demo#1]
Tried to get this up and running and first encountered a problem with the Makefile with the following error:

`make: *** No rule to make target 'client.wasm', needed by 'all'.  Stop`

So instead I just copied the make commands and ran in the terminal

Then when you get to 

`go run server.go`

I encounter the following issue:

`fork/exec /tmp/go-build4051260988/b001/exe/server: exec format error`

Any help would be appreciated!

**Comment by macknight** [comment]
when run "make" inside WSL of Win10,
I have this error:

![image](https://user-images.githubusercontent.com/754293/184480639-591d7cda-953f-4b18-aacd-25a9df8f984e.png)
 How to solve it?

BR

**Comment by macknight** [comment]
> So instead I just copied the make commands and ran in the terminal

what do you mean by "So instead I just copied the make commands and ran in the terminal"?
just "make" ?


I have the same error when running "make" inside WSL of Win10 under the code root folder.

**make: *** No rule to make target 'client.wasm', needed by 'all'.  Stop.**

How could I resolve this?


And if I ignore this error and run "go run server.go", then other errors occur.

![image](https://user-images.githubusercontent.com/754293/184488570-faf9c755-c1cc-4582-acbe-d8ca40cdfe75.png)


BR

**Comment by ChristianMct** [comment]
There was an error in the file/target names in the `Makefile`.  The latest commit should fix it (you might need to re-clone the repository).

Let me know if this doesn't solve all the issues.

**Comment by macknight** [comment]
> There was an error in the file/target names in the `Makefile`. The latest commit should fix it (you might need to re-clone the repository).
> 
> Let me know if this doesn't solve all the issues.

Hi Christian,
I'm using Win10.
After run "make", it has below error:
![image](https://user-images.githubusercontent.com/754293/186802438-0a990ca5-08b4-47c8-9e0e-925c55c68556.png)

So I have to run the commands before:
$Env:GOOS="js"
$Env:GOARCH="wasm"
and remove these env setting in Makefile:
.DEFAULT_GOAL := all

GOROOT=$(shell go env GOROOT)

client.wasm:
	go build -o server/static/client.wasm client/client.go

server/static/wasm_exec.js:
	cp "$(GOROOT)/misc/wasm/wasm_exec.js" server/static/wasm_exec.js

all: server/static/wasm_exec.js client.wasm


then it make successfully.
![image](https://user-images.githubusercontent.com/754293/186806774-8aa4fc2a-780e-44ee-a1da-5f21860cd931.png)


But when I run below commands, still some error:
cd server
go run server.go

![image](https://user-images.githubusercontent.com/754293/186806478-66524136-8410-47de-a175-6adcee09a743.png)

How should I resolve this?

BR

**Comment by ChristianMct** [comment]
This error is triggered because your modified make script changes the GOOS and GOARCH variables without setting them back to the original ones. Closing your terminal and re-opening a new one, then run the `go run` command should fix the problem.

In general, I would not recommend using the `Makefile` in Windows. Here are the steps I took to build and run the project without `make`.

```
set GOOS=js
set GOARCH=wasm
go build -o server/static/client.wasm client/client.go
```

Then close the terminal and open a new one OR run (but note that depending on your system, GOARCH could be something else).
```
set GOOS=windows
set GOARCH=amd64
```

Then I manually copied the `wasm_exec.js` file to the `server/static` folder. You can find your GOROOT from the `go env` command. Then navigate to `$(GOROOT)/misc/wasm/`.

After that, you should be able to navigate to the `server` folder and run `go run server.go`.

**Comment by macknight** [comment]
> This error is triggered because your modified make script changes the GOOS and GOARCH variables without setting them back to the original ones. Closing your terminal and re-opening a new one, then run the `go run` command should fix the problem.
> 
> In general, I would not recommend using the `Makefile` in Windows. Here are the steps I took to build and run the project without `make`.
> 
> ```
> set GOOS=js
> set GOARCH=wasm
> go build -o server/static/client.wasm client/client.go
> ```
> 
> Then close the terminal and open a new one OR run (but note that depending on your system, GOARCH could be something else).
> 
> ```
> set GOOS=windows
> set GOARCH=amd64
> ```
> 
> Then I manually copied the `wasm_exec.js` file to the `server/static` folder. You can find your GOROOT from the `go env` command. Then navigate to `$(GOROOT)/misc/wasm/`.
> 
> After that, you should be able to navigate to the `server` folder and run `go run server.go`.

Thanks, I'll have a try.

**Comment by macknight** [comment]
server could run.
![image](https://user-images.githubusercontent.com/754293/187013016-a8a0b51a-5add-49d0-8976-2c09fe3f751e.png)

**Comment by assist726** [comment]
> There was an error in the file/target names in the `Makefile`. The latest commit should fix it (you might need to re-clone the repository).
> 
> Let me know if this doesn't solve all the issues.

Thanks! Latest commit fixed the issues on my side, gave up on running and Windows and just used WSL instead.
