### ISSUE TITLE
result issue

### ISSUE THREAD

**Issue by macknight** [ldsec/lattigo-polls-demo#2]
Hi,
![image](https://user-images.githubusercontent.com/754293/187013143-eff66894-80d2-4345-8555-90394f305791.png)
After poll, how to check the results? looks like no result is shown.

BR

**Comment by macknight** [comment]
![image](https://user-images.githubusercontent.com/754293/187019300-ebcb20d2-1180-4a5c-af89-0ef95d7f3176.png)
the command line doesn't have the poll's result, either.

**Comment by macknight** [comment]
What I expect to see is like below:
Monday: 2
....
Sunday: 1

**Comment by ChristianMct** [comment]
The expected result is a green tick mark at the intersections between all the schedule. 

![image](https://user-images.githubusercontent.com/5487944/187219905-fde41de3-2f9b-4472-a234-0d12c8fd21e6.png)
