### ISSUE TITLE
404 when re-run the server

### ISSUE THREAD

**Issue by macknight** [ldsec/lattigo-polls-demo#3]
Hi,
I re-run the server but the url shows 404?
![image](https://user-images.githubusercontent.com/754293/187954722-9fb081de-11b8-486e-8d55-e55422188f15.png)

BR

**Comment by ChristianMct** [comment]
Hi,

I agree it is not very intuitive, but the path for the home page is 
```
http://localhost:8080/polls
```
that, without the final `/`.

**Comment by ChristianMct** [comment]
I added the `/` and `/polls/` routes to prevent this issue.

**Comment by macknight** [comment]
![image](https://user-images.githubusercontent.com/754293/188104868-2075e62a-5ba7-4125-a527-c2a548484738.png)
Cool, It could run well. And the result looks good.

BR
