### ISSUE TITLE
Why can FHE decryption be seen as an approximate computation of the message ?

### ISSUE THREAD

**Issue by macknight** [ldsec/lattigo-polls-demo#7]
Hi,
![image](https://user-images.githubusercontent.com/754293/189059270-4b3b5595-49c7-4044-bfdd-5bbc60db500b.png)

since ct=(ct0, ct1)=(m+up0+e0, up1+e1),
then,
dec(s, ct)
=c0+sc1
=**m+up0+e0 + sup1+se1**
why does "m+up0+e0 + sup1+se1" approximately equal to below? simply because we have e0+s*e1 is small(<< q in absolute value)?

~ **m+up0+sup1**

BR

**Comment by ChristianMct** [comment]
This is correct.
